# Generated by Django 4.1.4 on 2023-04-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_currency_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
    ]
