# Generated by Django 4.1.4 on 2023-10-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_kyc_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank-transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("cryptocurrency", "Cryptocurrency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "crypto_gateway",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "crypto_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
