# Generated by Django 4.1.4 on 2023-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_currency_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
