# Generated by Django 4.1.4 on 2023-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_withdrawalmethod_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("denied", "Denied"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
