# Generated by Django 4.1.4 on 2023-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_withdrawal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
