# Generated by Django 4.1.4 on 2023-10-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_kyc_file2_alter_kyc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
