# Generated by Django 4.1.4 on 2023-10-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_kyc_created_at_kyc_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
