# Generated by Django 4.1.4 on 2023-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
