# Generated by Django 4.1.4 on 2023-05-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_platform_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="account_type",
        ),
        migrations.AddField(
            model_name="order",
            name="account_type",
            field=models.ManyToManyField(to="store.accounttype"),
        ),
    ]
