# Generated by Django 4.1.4 on 2023-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
