# Generated by Django 4.1.4 on 2023-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_order_account_type_order_account_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="discounted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
