# Generated by Django 4.1.4 on 2023-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_order_quantity_order_discounted_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
