# Generated by Django 4.1.4 on 2023-10-17 21:49

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.PositiveIntegerField(
                default=store.models.Order.generate_unique_id,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
