# Generated by Django 4.1.4 on 2023-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_billingdetail_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(max_length=20),
        ),
    ]
