# Generated by Django 4.1.4 on 2023-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
