# Generated by Django 4.1.4 on 2023-10-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="department",
            field=models.CharField(
                choices=[
                    ("account-type", "account-type"),
                    ("enquiry", "Enquiry"),
                    ("funding", "Funding"),
                    ("withdrawal", "Withdrawal"),
                    ("order", "Order"),
                    ("payment-method", "Payment-method"),
                ],
                default="enquiry",
                max_length=40,
                null=True,
            ),
        ),
    ]
