# Generated by Django 4.1.4 on 2023-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0003_ticket_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open"), ("close", "Close")],
                default="open",
                max_length=10,
            ),
        ),
    ]
