# Generated by Django 4.1.4 on 2023-10-17 22:31

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.PositiveIntegerField(
                default=ticket.models.Ticket.generate_unique_id,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
